-- RUN THIS SQL IN YOUR SUPABASE SQL EDITOR TO CREATE TABLES

-- 1. Create Menu Items Table
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text not null, -- 'Starters', 'Main Course', etc.
  image_url text,
  available boolean default true,
  is_popular boolean default false,
  is_veg boolean default true,
  is_spicy boolean default false
);

-- 2. Create Reservations Table
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  reservation_date date not null,
  reservation_time time not null,
  guests integer not null,
  status text default 'Pending', -- 'Pending', 'Confirmed', 'Cancelled'
  notes text
);

-- 3. Create Orders Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'Pending', -- 'Pending', 'Preparing', 'Ready', 'Delivered', 'Cancelled'
  customer_name text,
  address text,
  phone text,
  total_amount numeric,
  notes text,
  payment_method text default 'COD' -- 'COD', 'UPI', 'Card'
);

-- 4. Create Order Items Table (Junction Table)
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  menu_item_id bigint references public.menu_items(id) on delete set null, -- Keep record even if item deleted
  quantity integer not null,
  price_at_time numeric not null, -- Store price at time of order
  menu_item_name text -- Redundant but useful for historical display if item deleted
);

-- 5. Create Row Level Security (RLS) Policies
alter table public.menu_items enable row level security;
alter table public.reservations enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Allow public read access for Menu
create policy "Public Menu Read" on public.menu_items for select using (true);
-- Allow ANYONE to edit menu for MVP testing (Restore auth later)
create policy "Admin Menu All" on public.menu_items for all using (true);

-- Allow public insert for Reservations (Guests booking table)
create policy "Public Reservation Insert" on public.reservations for insert with check (true);
-- Allow ANYONE to view reservations for MVP testing
create policy "Admin Reservation All" on public.reservations for all using (true);

-- Allow public insert for Orders (Guests ordering food)
create policy "Public Order Insert" on public.orders for insert with check (true);
-- Allow ANYONE to view orders for MVP testing (Admin Dashboard)
create policy "Admin Order All" on public.orders for all using (true);

-- Allow public insert for Order Items (Guests items)
create policy "Public Order Items Insert" on public.order_items for insert with check (true);
-- Allow ANYONE to view order items for MVP testing (Admin Dashboard)
create policy "Admin Order Items All" on public.order_items for all using (true);

-- 6. Create Storage Bucket for Menu Images (Use ON CONFLICT to avoid error if exists)
insert into storage.buckets (id, name, public) values ('menu-images', 'menu-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
create policy "Public Access Menu Images" on storage.objects for select using ( bucket_id = 'menu-images' );
create policy "Admin Upload Menu Images" on storage.objects for insert with check ( bucket_id = 'menu-images' );

-- 7. Create Feedbacks Table
create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  rating integer not null, -- 1 to 5
  message text,
  contact_info text -- Optional email or phone
);

-- Enable RLS
alter table public.feedbacks enable row level security;

-- Policies
create policy "Public Feedback Insert" on public.feedbacks for insert with check (true);
create policy "Admin Feedback Read" on public.feedbacks for select using (true);

-- 8. Add Dine-in Support (Run if you already created tables)
alter table public.orders add column if not exists order_type text default 'Delivery'; -- 'Delivery', 'Pickup', 'Dine-in'
alter table public.orders add column if not exists table_no text; -- For Dine-in

-- 9. Create Settings Table
create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  restaurant_name text default 'The Rooftop Restaurant',
  address text default '123 Skyline Ave, City Center',
  phone text default '+91 123 456 7890',
  table_count integer default 10,
  delivery_fee numeric default 50,
  notifications_enabled boolean default true
);

-- Enable RLS
alter table public.settings enable row level security;

-- Policies
create policy "Public Settings Read" on public.settings for select using (true);
create policy "Admin Settings All" on public.settings for all using (true);

-- Insert default row if not exists
insert into public.settings (id, restaurant_name) values (1, 'The Rooftop Restaurant')
on conflict (id) do nothing;



