-- Add Hero Section content to settings table
ALTER TABLE settings 
ADD COLUMN IF NOT EXISTS hero_title text DEFAULT 'Experience Dining at New Heights',
ADD COLUMN IF NOT EXISTS hero_subtitle text DEFAULT 'The Rooftop Restaurant',
ADD COLUMN IF NOT EXISTS hero_description text DEFAULT 'Indulge in a culinary journey with breathtaking views. Our chefs prepare exquisite dishes using the finest local ingredients.',
ADD COLUMN IF NOT EXISTS hero_cta_text text DEFAULT 'Book A Table';

-- Create Features table for dynamic services/features section
CREATE TABLE IF NOT EXISTS features (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    icon text not null default 'Star', -- Lucide icon name
    display_order int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on features
ALTER TABLE features ENABLE ROW LEVEL SECURITY;

-- Create policies for features
CREATE POLICY "Enable read access for all users" ON features
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON features
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON features
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON features
    FOR DELETE USING (auth.role() = 'authenticated');

-- Insert default features if table is empty
INSERT INTO features (title, description, icon, display_order)
SELECT 'Signature Cocktails', 'Handcrafted mocktails and beverages designed to perfectly complement your evening under the stars.', 'GlassWater', 1
WHERE NOT EXISTS (SELECT 1 FROM features);

INSERT INTO features (title, description, icon, display_order)
SELECT 'Authentic Cuisine', 'A fusion of local flavors and modern culinary techniques, sourcing the freshest ingredients daily.', 'Utensils', 2
WHERE NOT EXISTS (SELECT 1 FROM features);

INSERT INTO features (title, description, icon, display_order)
SELECT 'Panoramic Views', 'The perfect sunset spot in Kahalgaon, offering breathtaking views of the city skyline and river.', 'View', 3
WHERE NOT EXISTS (SELECT 1 FROM features);
