-- Add featured column to menu_items
ALTER TABLE public.menu_items
ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false;

-- Create testimonials table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id bigint generated by default as identity primary key,
    name text not null,
    rating int not null check (rating >= 1 and rating <= 5),
    message text not null,
    source text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create gallery_images table
CREATE TABLE IF NOT EXISTS public.gallery_images (
    id bigint generated by default as identity primary key,
    image_url text not null,
    caption text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add updated_at trigger helper if not exists
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Policies for Testimonials
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.testimonials
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.testimonials
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON public.testimonials
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON public.testimonials
    FOR DELETE USING (auth.role() = 'authenticated');

-- Policies for Gallery
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.gallery_images
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.gallery_images
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON public.gallery_images
    FOR DELETE USING (auth.role() = 'authenticated');
